### ISSUE TITLE
Designer suggests improvements or thumbs

### ISSUE THREAD

**Issue by avidrucker** [avidrucker/autofocus-exp#133]
Designer writes or thumbnails, and submits RFI suggestions for web app design

**Comment by kaerudesigns** [comment]
The concept of the layout is good in its concept stage. Some ideas to consider are drop down menus to add breathing room and key icons to replace certain text.

My main concern for the layout is how this would look on different formats, Is this meant for an IOS? If so, how would it look on say an Iphone? Scrolling could be an issue which many people dislike and is difficult to do on a small screen. Same could be asked for on a PC.

**Comment by avidrucker** [comment]
@kaerudesigns Thanks for your layout suggestions!

If I understand you right, here are the concerns to consider:

1. Designer adds menu to web app design: benefits: more space to use elsehow in the app (see breathing room)
2. Designer add icons to design : benefits: improved readability, a11y, and app friendliness
   A. ascii symbols for command line app
   B. unicode emoji for web app
3. Designer creates breathing room in web app layout: benefits: improved readability, aesthetics
4. Architect makes a call on the offered screen sizes & display types to be delivered to the user: benefits: clear direction & save time not over-engineering for too many screens/devices

Do I understand you about right?

**Comment by avidrucker** [comment]
> My main concern for the layout is how this would look on different formats, Is this meant for an IOS? If so, how would it look on say an Iphone? Scrolling could be an issue which many people dislike and is difficult to do on a small screen. Same could be asked for on a PC.

@kaerudesigns This app will be for responsive web, meaning, that we will have first a web app, or web page, that looks good (is designed for) small screens such as iPhones. Initially, as per the current Figma doc, we will design for 360 width by 640 height (in pixels). After that design is more polished, we will likely create a desktop layout, and then, if that goes well, a mid-sized tablet layout (for a total of 3 supported device sizes).

**Comment by kaerudesigns** [comment]
Well...
1. Yeah, exactly right,  hidden menus not only add breathing room but offers better organization for navigating pages.
2. Adding icons not only increases space but also offers more of a universal language for those who's 1st language may be different.
3. There may be other ways to offer comfortable reading such as choosing the right font or color scheme.

Ah ok, knowing the dimensions will determine how the layout will look so that works.

**Comment by avidrucker** [comment]
@kaerudesigns Please hold for issue processing.

**Comment by avidrucker** [comment]
@kaerudesigns You helped me realize I should have a roadmap. It's in the request log #153 now. Also: #158 is being addressed, and #159 reflects an update to the front page `README.md`.

Please note the following items were added to the ice-box, and they are **not** yet open tasks available to work on for compensation: #154, #155, #156, #157, #160.

Please look out for a payment for 15 min * your hourly rate.
