### ISSUE TITLE
Payment Methods

### ISSUE THREAD

**Issue by lFanto** [avidrucker/autofocus-exp#173]
I had questions regarding payment. If i were to do work on this project, how would i be paid? if this is by hourly, how would they be tracked? In what method would i be paid? for example, through paypal?
Lastly, how many hours should i contribute per week to this project?

**Comment by avidrucker** [comment]
> If i were to do work on this project, how would i be paid? In what method would i be paid? for example, through paypal?

Ideally by Venmo, though I can also pay via PayPal too. Please email me directly your payment info.

> if this is by hourly, how would they be tracked?

This is tracked by pull requests made by issue. Issues are marked with a time amount. So, for example, if you push successfully code for a 30 minute issue, I will compensate you for your hourly rate * 0.5

> Lastly, how many hours should i contribute per week to this project?

You contribute as many hours as you like, for issues that are **already posted and approved to start work on**. In other words, you can only contribute as many hours as there are **open issues**. Please note that the current open issues are under the milestone `mvp-demo`

**Comment by avidrucker** [comment]
@lFanto You can also search for issues that relevant for you now with this search query: `is:open is:issue milestone:mvp-demo label:development ` or click on this link for [the currently open issues](https://github.com/avidrucker/autofocus-exp/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+milestone%3Amvp-demo+label%3Adevelopment+)

**Comment by avidrucker** [comment]
@lFanto Please see [this issue thread](https://github.com/avidrucker/autofocus-exp/issues/133) as an example of work approved, submitted, and paid for. It's a designer task, but the payment process is the same as for developers.

**Comment by avidrucker** [comment]
Marking closed for now, feel free to comment regarding further payment related questions.
