### ISSUE TITLE
Suggestion: Review of the video in readme

### ISSUE THREAD

**Issue by kaerudesigns** [avidrucker/autofocus-exp#178]
[Edited by project maintainer]

**Comment by avidrucker** [comment]
@kaerudesigns You're approved to write your own review of the video, I think this would add a lot of value to the project. I'm pricing it at 30 min of work.

**Comment by kaerudesigns** [comment]
The following is a review for my opinion of "Yegor256's conference talk "eXtremely Distributed Software Development", at DevTernity."

Watch the video here: https://www.youtube.com/watch?v=7EytYc7K5JA

Paying your employees exactly how much they work, not how much time they spend at the office. This method i believe is great if you want to get the most out of your employees

1. Teamwork
Eliminating teamwork on projects and assigning individual tasks based on the employee's knowledge and work load is a good idea. Assigning the same amount of work for those on different grade levels could ideally leave the lesser skilled employees stressed and the more experienced ones wanting more. Assigning tasks to individuals would make them solely responsible for what needs to be done, pushing themselves to get it done.

2. Overtime
The idea of working 3-4hrs a day is good... in theory. While working a 9-5 job isnt great, it does allow for a more flexible schedule for people to resolve multiple issues within a set time period. Working past that is not recommended though as A) people are usually too tired to continue working past their set times. and B) Companies start expecting you to keep working overtime.

If you want a better idea of my feelings of overtime and time efficiency in a work environment, please watch this video: https://www.youtube.com/watch?v=9bvcyGyzj7Y (Some light swearing in it).

3. Learning
 While having an expert in a certain field can be good, it can be a double edge sword, while they can get the job done efficiently, that means only _they_ can get the job done efficiently, leaving the other employees lost. Rotating tasks will allow other employees to learn and fix many of the issues in the field and let them grow. If they don't understand a task, then i believe its both the responsibility of both the giver and receiver of the task to understand together, rather then what was said in the video of only the giver to learn more about the task at hand. That way they would both understand the initial issue when it appears again.

4. Meetings
I do agree that there is a need to eliminate meetings. Anything that takes longer than 5min or so is time that the employees can't work. Whatever is needed to be said can be put on a document for those to be read on their own time.
But... there's still a need to communicate. If a file or a simple task is needed quickly then its better to talk to the person directly and ask for the issue to be resolved asap. Putting in a request is more time consuming as Person A would have no choice but to sit and wait for Person B to hopefully read and understand the request and then make a time slot to do the request and then get back to Person A and hope Person A would read it and understand the reply. Something that could've been resolved in less than 5min could take hours to do depending on each other's schedule.

5. Salaries
I see the value of eliminating salaries and setting up micro-payments for micro-tasks. No more wasted time and its sets up a fast, efficient work system for small business. I don't see this model working for bigger companies as this would require micromanaging to ensure that all the employees are working at all times. And what if a break is needed? Not being paid during breaks would result in fewer employees taking breaks which increases stress. The system works, but to a certain extent which raises other issues.

So as a summary, the system shown in the presentation has holes in certain areas which clashes with the traditional work system and with big business models. On a small scale however, micro-tasking lets the employees to work at their best during the few prime hours a day they have with few distractions as the pay-per minute system allows better focus and payment.

**Comment by avidrucker** [comment]
@kaerudesigns Thank you for your thoughtful and thorough review. I'm marking this as completed and closed for now, and will link it so others may read it instead of watching the video ;)

**Comment by avidrucker** [comment]
@kaerudesigns Please confirm with a thumbs up you've received payment.

**Comment by avidrucker** [comment]
[Review has been posted](https://github.com/avidrucker/autofocus-exp/blob/master/docs/video_review.md), thanks @kaerudesigns !
