### ISSUE TITLE
Dev makes desktop app port using Electron

### ISSUE THREAD

**Issue by themadarchitect** [avidrucker/autofocus-exp#313]
This makes more business than to build it as a web app. If todo items are to be tracked locally in the first place, there isn't a deep need for this to be a web app, per se. This will also eliminate potential accidental cache deletion issues.

**Comment by avidrucker** [comment]
Leaving a record here that we're switching gears just for this week to have the demo made available as a web app first. I'm thinking of this is a minor detour (adding a new point in the trip) rather than a complete change of direction.
