### ISSUE TITLE
Dev refactors codebase to conform to fp semantics

### ISSUE THREAD

**Issue by themadarchitect** [avidrucker/autofocus-exp#335]
### Reference libraries to support functional programming refactor
- https://github.com/gcanti/fp-ts
- https://github.com/gcanti/io-ts

**Comment by avidrucker** [comment]
Quick questions: How will this impact on-boarding of new devs (ie. how many new structures, concepts, micro-patterns will be used)? Which issues in particular (such as serialization/deserialization) is this refactoring necessary/beneficial for?
