### ISSUE TITLE
Designer creates 3-6 thumbnails to give their own personal redesign

### ISSUE THREAD

**Issue by avidrucker** [avidrucker/autofocus-exp#404]
Specifically, I would like to get photographs of hand-drawn sketches which show the result of brainstorming different layouts, different design ideas to show the lists in different ways, and organize the buttons and menus and headers in other ways that might be better. Lastly, please add 1 comment per sketch/idea to make clear what is the change/design/ideas as well as the goal/effect (for example: moving the back button to always be in the upper left corner, and never at the bottom of the screen, to keep it consistent, and not double up on same functionality)

Pre-req for issue #403

**Comment by kaerudesigns** [comment]
What do you mean by thumbnails.

**Comment by avidrucker** [comment]
@kaerudesigns By thumbnails, I mean rough designs, handdrawn or digital too is fine, something like the rough screen design sketches here: https://karenkavett.com/blog/737/graphic-design-without-a-computer-part-2.php

**Comment by kaerudesigns** [comment]
Please see the following link for the design prototype.
[https://www.figma.com/file/lBgFhUEOcqL7uq0peKXy6I/Autofocus?node-id=0%3A1]

Please see Images as references.

![Whatsapp](https://user-images.githubusercontent.com/53319587/79586957-d5012980-809f-11ea-9c85-368d1245cdfb.jpg)
![To do list](https://user-images.githubusercontent.com/53319587/79586959-d599c000-809f-11ea-845e-d8b291d33d46.jpg)
![Reminders](https://user-images.githubusercontent.com/53319587/79586960-d599c000-809f-11ea-943d-e29698a0a0e4.jpg)

**Comment by avidrucker** [comment]
@kaerudesigns Could you please note the context behind each reference screen (what you felt was relevant and/or why you used it)?

**Comment by avidrucker** [comment]
@kaerudesigns Also, these don't appear to be thumbnails, as they have color, and show the full app design with fonts, and "actual app design" aesthetic. Did you mean for these to be more a rough, loose interpretation?

**Comment by avidrucker** [comment]
Marking this issue as not resolved just yet, and still open for submissions, please see the updated comment for specific instructions,
