### ISSUE TITLE
Writer improves on copy content on portfolio website

### ISSUE THREAD

**Issue by avidrucker** [avidrucker/autofocus-exp#441]
- [ ] Writer reviews copy content (text only) on this page: https://avidrucker.carbonmade.com/autofocus
- [ ] Writer submits their edits, revisions, comments, question etc. as a Google Docs link posted on this issue

**Comment by caryfado** [comment]
hi!

**Comment by caryfado** [comment]
https://docs.google.com/document/d/1mpzGdwzZ0w57Z7p4fBeLHe_qt8LzJowaeqbbo6k1cTE/edit?usp=sharing
