### ISSUE TITLE
Founder consults writer on writing improvements

### ISSUE THREAD

**Issue by avidrucker** [avidrucker/autofocus-exp#442]
- [x] Founder discusses with writer opportunities to improve writing components of the project such as the portfolio website

**Comment by avidrucker** [comment]
@caryfado Please expect compensation in the next 5 minutes, and please let me know via comment that it came through :smile:

**Comment by caryfado** [comment]
got it!

**Comment by avidrucker** [comment]
Marking as resolved, thank you @caryfado !
